/* eslint-disable prettier/prettier */
import { StyleSheet } from "react-native";

const GlobalStyles= StyleSheet.create({
    bg1:{
        backgroundColor:"#ED5E28"
    },
    bg2:{
        backgroundColor:"#C1D37F"
    },
    bg3:{
        backgroundColor:"#333333"
    },
    bg4:{
        backgroundColor:"white"
    },
    bg5:{
        backgroundColor:"#EBEEF5"
    },
    fc1:{
        color:"black"
    },
    fc2:{
        color:"white"
    },
    fc3:{
        color:"#333333"
    },
    fc4:{
        color:"#ED5E28"
    },
    fc5:{
        color:"#C1D37F"
    },
    ff1:{
        fontFamily:"Roboto"
    },
    ff2:{
        fontFamily:"sans-serif-condensed"
    },
    wH100:{
        width:"100%",
        height:"100%",
    },
    flexCC:{
        flex:1,
        justifyContent:'center',
        alignItems:"center"
    },
    mt1:{
        marginTop:10
    },
    mt2:{
        marginTop:15
    },
    mt3:{
        marginTop:20
    },
    mt4:{
        marginTop:25
    },
    mt5:{
        marginTop:30
    },
    mb1:{
        marginBottom:10
    },
    mb2:{
        marginBottom:15
    },
    mb3:{
        marginBottom:20
    },
    ml1:{
        marginLeft:10
    },
    ml2:{
        marginLeft:15
    },
    ml3:{
        marginLeft:20
    },
    mr1:{
        marginRight:10
    },
    mr2:{
        marginRight:15
    },
    mr3:{
        marginRight:20
    },
    mh1:{
        marginHorizontal:10
    },
    mh2:{
        marginHorizontal:15
    },
    mh3:{
        marginHorizontal:20
    },
    mv1:{
        marginVertical:10
    },
    mv2:{
        marginVertical:15
    },
    mv3:{
        marginVertical:20
    },
    m0:{
        margin:0
    },
    p0:{
        padding:0
    },
    pt1:{
        paddingTop:10
    },
    pt2:{
        paddingTop:15
    },
    pt3:{
        paddingTop:20
    },
    pb1:{
        paddingBottom:10
    },
    pb2:{
        paddingBottom:15
    },
    pb3:{
        paddingBottom:20
    },
    pl1:{
        paddingLeft:10
    },
    pl2:{
        paddingLeft:15
    },
    pl3:{
        paddingLeft:20
    },
    pr1:{
        paddingRight:10
    },
    pr2:{
        paddingRight:15
    },
    pr3:{
        paddingRight:20
    },
    ph1:{
        paddingHorizontal:10
    },
    ph2:{
        paddingHorizontal:15
    },
    ph3:{
        paddingHorizontal:20
    },
    pv1:{
        paddingVertical:10
    },
    pv2:{
        paddingVertical:15
    },
    pv3:{
        marginVertical:20
    },
    opacity8:{
        opacity:0.8
    },
    opacity6:{
        opacity:0.6
    },
    opacity4:{
        opacity:0.4
    },
    opacity2:{
        opacity:0.2
    },
    br1:{
        borderRadius:5
    },
    br2:{
        borderRadius:10
    },
    fz1:{fontSize:5},
    fz2:{fontSize:10},
    fz3:{fontSize:15},
    fw1:{fontWeight:"200"},
    fw2:{fontWeight:"400"},
    fw3:{fontWeight:"600"},
    fw4:{fontWeight:"800"},
    fw5:{fontWeight:"900"},
    input1: {
      height: 40,
      width:350,
      borderRadius:10
    }
});
export default GlobalStyles;